//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace paginaweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registrarse
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string usuario { get; set; }
        public string clave1 { get; set; }
        public string clave2 { get; set; }
        public string email { get; set; }
        public string sexo { get; set; }
        public string pais { get; set; }
        public Nullable<System.DateTime> fecha_de_nacimiento { get; set; }
        public string foto { get; set; }
        public string caracteristica { get; set; }
    }
}
