//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace paginaweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagina
    {
        public int id { get; set; }
        public string inicio { get; set; }
        public string noticias { get; set; }
        public string imagenes { get; set; }
        public string contacto { get; set; }
    }
}
